version: '3.8'

services:
  service-manager-database:
    container_name: 'service-manager-database'
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service-manager-database
